/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ictproject;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sandeep
 */
public class SauchalayKoAwasta extends javax.swing.JFrame {

    /**
     * Creates new form SauchalayKoAwasta
     */
    public SauchalayKoAwasta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        gabisakoNaam = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("गाविसको नाम ");

        gabisakoNaam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gabisakoNaamActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "1", null, null, null, null, null, null, null, null, null, null, null},
                {"2", "2", null, null, null, null, null, null, null, null, null, null, null},
                {"3", "3", null, null, null, null, null, null, null, null, null, null, null},
                {"4", "4", null, null, null, null, null, null, null, null, null, null, null},
                {"5", "5", null, null, null, null, null, null, null, null, null, null, null},
                {"6", "6", null, null, null, null, null, null, null, null, null, null, null},
                {"7", "7", null, null, null, null, null, null, null, null, null, null, null},
                {"8", "8", null, null, null, null, null, null, null, null, null, null, null},
                {"9", "9", null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "<html>सि.<br>नं. ", "<html>वडा नं.<br", "<html>अस्थायी चर्पी <br>संख्या", "<html>स्थायी चर्पी संख्या<br>", "<html>चर्पी नभएको संख्या<br>", "<html>खुल्ला दिसामूक्त घोषण<br>भएको/नभएको ", "<html>खुल्ला दिसामूक्त घोषण<br>भएको भए मिति", "<html>पिसाव अलग गर्ने <br>घरधुरी  संख्या", "<html>पिसाव मल प्रयोग <br>गर्ने घरधुरी  संख्या", "<html>बायो ग्यास चर्पी <br>प्रयोग गर्ने घरधुरी ", "<html>धुँवारहित चुल्हो<br> भएको घर संख्या", "<html>धुँवारहित वडा <br>घोषण  भएको/नभएको", "कैफियत"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setDragEnabled(true);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(12).setResizable(false);
        }

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(gabisakoNaam, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gabisakoNaam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gabisakoNaamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gabisakoNaamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gabisakoNaamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        String gabisaName=gabisakoNaam.getText();
        
        for(int i=0;i<9;i++){
        try{
        PreparedStatement updateemp = JDBCConnection.conn.prepareStatement
        ("insert into  sauchalaykoawasta(sno,wardNo,temporaryToilet,permanentToilet,noToilet,bhakonaBhako,bhakonaDate,urineSeperation,urineManure,bioGasUse,noSmokeGas,noSmokeWard,remarks,name) "
                + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

        updateemp.setInt(1,Integer.parseInt(model.getValueAt(i,0).toString()));
        updateemp.setInt(2,Integer.parseInt(model.getValueAt(i,1).toString()));
        updateemp.setInt(3,model.getValueAt(i,2)==null?0:Integer.parseInt(model.getValueAt(i,2).toString()));
        updateemp.setInt(4,model.getValueAt(i,3)==null?0:Integer.parseInt(model.getValueAt(i,3).toString()));
        updateemp.setInt(5,model.getValueAt(i,4)==null?0:Integer.parseInt(model.getValueAt(i,4).toString()));
        updateemp.setString(6,model.getValueAt(i,5)==null?"":model.getValueAt(i,5).toString());
        updateemp.setString(7,model.getValueAt(i,6)==null?"":model.getValueAt(i,6).toString());
        updateemp.setInt(8,model.getValueAt(i,7)==null?0:Integer.parseInt(model.getValueAt(i,7).toString()));
        updateemp.setInt(9,model.getValueAt(i,8)==null?0:Integer.parseInt(model.getValueAt(i,8).toString()));
        updateemp.setInt(10,model.getValueAt(i,9)==null?0:Integer.parseInt(model.getValueAt(i,9).toString()));
        updateemp.setInt(11,model.getValueAt(i,10)==null?0:Integer.parseInt(model.getValueAt(i,10).toString()));
        updateemp.setInt(12,model.getValueAt(i,11)==null?0:Integer.parseInt(model.getValueAt(i,11).toString()));
        updateemp.setString(13,model.getValueAt(i,12)==null?"":model.getValueAt(i,12).toString());
        updateemp.setString(14,gabisaName);
        
        updateemp.executeUpdate();
            
        }catch(SQLException se){
      //Handle errors for JDBC
      se.printStackTrace();
   }catch(Exception e){
      //Handle errors for Class.forName
       e.printStackTrace();
       break;

   }}
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SauchalayKoAwasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SauchalayKoAwasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SauchalayKoAwasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SauchalayKoAwasta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SauchalayKoAwasta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gabisakoNaam;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
